#!/usr/bin/env sh
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gyr AT protonmail DOT ch>
# File:   gyr-ssh-init
# Update: 20100815 14:29:48
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: start up ssh-agent and gpg-agent
# Usage: gyr-ssh-init
#
################################################################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

[ $# -ne 0 ] && { gyr-print -e ${0##*/}; exit 1; }

# SSH - reset sharing of multiple sessions over a single network connection.
gyr-print -i "Resetting ssh mulitple sessions sharing..."
for i in ${HOME}/.ssh/master-*; do
    rm -v $i |:
done

### START-SSH ###
gyr-print -i "Terminating any previous ssh-agent..."
eval $(ssh-agent -k)
ssh-agent -k |:
killall ssh-agent |:
gyr-print -i "Starting ssh-agent..."
eval $(ssh-agent)
gyr-print -i "Adding ssh keys..."
ssh-add
gyr-print -i "Keys added:"
ssh-add -l
### End-SSH ###

### START-GPG ###
gyr-print -i "Terminating any previous gpg-agent..."
killall gpg-agent |:
gyr-print -i "Starting ssh-agent"
eval $(gpg-agent --daemon)
# B0E4F0BA
### End-GPG ###
