#!/bin/bash
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gustavoyr+scripts AT gmail DOT com>
# File:  gyr-ncmpcpp
# Update: 20110217 17:23:08
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: ncmpcpp wrapper
# Usage: gyr-ncmpcpp
#
################################################################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

[ $# -ne 0 ] && { gyr-print -e ${0##*/}; exit 1; }

DIR_SOURCE='/work/gyr/.confm'
DIR_MOUNTING_POINT='/work/gyr/dmus'

#[ -d ${DIR_SOURCE} ] || { gyr-print -e ${0##*/} "Source dir ${DIR_SOURCE} does not exist."; exit 1; }
[ -d ${DIR_MOUNTING_POINT} ] || { gyr-print -e ${0##*/} "Mounting point dir ${DIR_MOUNTING_POINT} does not exist."; exit 1; }

#if ps -U mpd -u mpd | grep mpd >/dev/null 2>&1; then
if pgrep -u mpd mpd >/dev/null 2>&1; then
    sudo mpd --kill
    mpd
#elif ! ps -U ${USER} -u ${USER} | grep mpd >/dev/null 2>&1; then
elif ! pgrep -u ${USER} mpd >/dev/null 2>&1; then
    mpd
fi

if [ -d "${DIR_SOURCE}" ]; then
    if ! mount | cut -d ' ' -f1 | grep ${DIR_SOURCE} >/dev/null 2>&1; then
        sudo mount -t ecryptfs ${DIR_SOURCE} ${DIR_MOUNTING_POINT} -o key=passphrase,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_passthrough=n,ecryptfs_enable_filename_crypto=y
        sudo mpd --kill
        mpd
    fi
    if mount | cut -d ' ' -f1 | grep ${DIR_SOURCE} >/dev/null 2>&1; then
        ncmpcpp
    else
        gyr-print -e ${0##*/} "Failed to mount ${DIR_MOUNTING_POINT}"
        exit 1
    fi
else
    ncmpcpp
fi
