#!/bin/bash
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gustavoyr+scripts AT gmail DOT com>
# File:  gyr-vnc-ssh-single
# Update: 20101229 13:33:08
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Single use vnc-over-ssh connection
# Usage: gyr-vnc-ssh-single <hostname>
#
################################################################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

[ $# -ne 1 ] && { gyr-print -e ${0##*/}; exit 1; }

HOSTNAME=$1

ssh -f -L 5900:localhost:5900 ${HOSTNAME} "x11vnc -safer -localhost -nopw -once -display :0" && vinagre localhost:5900
