#!/usr/bin/env bash
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gustavoyr+scripts AT gmail DOT com>
# File:  gyr-xterm-dropdown-launcher
# Update: 20110319 09:47:07
# (C) Copyright 2011 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Launch xterm-dropdown
# Usage: gyr-xterm-dropdown-launcher
#
################################################################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

[ $# -ne 0 ] && { gyr-print -e ${0##*/} "Syntax error"; exit 1; }

if [ -f ~/.yaql.pid ]; then
    bash -c 'kill -USR1 $(cat ~/.yaql.pid)'
else
    xterm -e ${GYR_PATH}/scripts/gyr-screen XTERMDROPDOWN
fi
