#!/usr/bin/env sh
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gyr AT protonmail DOT ch>
# File: gyr-progress-bar
# Update: 20100814 10:48:25
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: 
# Usage: 
#
################################################################################

#strace -q -ewrite $e 2>&1 \
#    | awk '{
#        count += $NF
#        if (count % 10 == 0) {
#            percent = count / total_size * 100
#            printf "%3d%% [", percent
#            for (i=0;i<=percent;i++)
#                printf "="
#            printf ">"
#            for (i=percent;i<100;i++)
#                printf " "
#            printf "]\r"
#        }
#    }
#    END { print "" }' total_size=$(stat -c '%s' "${1}") count=0
#cp_p()
#{
   strace -q -ewrite cp -- "${1}" "${2}" 2>&1 \
      | awk '{
        count += $NF
            if (count % 10 == 0) {
               percent = count / total_size * 100
               printf "%3d%% [", percent
               for (i=0;i<=percent;i++)
                  printf "="
               printf ">"
               for (i=percent;i<100;i++)
                  printf " "
               printf "]\r"
            }
         }
         END { print "" }' total_size=$(stat -c '%s' "${1}") count=0
#}
