#!/usr/bin/env bash
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gyr AT protonmail DOT ch>
# File:  gyr-ubuntu-one-sync
# Update: 20110406 15:03:55
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Sync ~/.gyr.d with ubuntu one dir, excluding .hg dir
# Usage: gyr-ubuntu-one-sync
#
################################################################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

[ $# -ne 0 ] && { gyr-print -e ${0##*/}; exit 1; }

if [ -d ~/Ubuntu\ One ]; then
    rsync -avz --delete --exclude '~/.gyr.d/.hg/*' --exclude '~/.gyr.d/.git/*' ~/.gyr.d ~/Ubuntu\ One
fi
