#!/usr/bin/env bash
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gyr AT protonmail DOT ch>
# File:  gyr-xterm-dropdown-reset
# Update: 20110319 09:54:45
# (C) Copyright 2011 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Reset xterm-dropdown
# Usage: gyr-xterm-dropdown-reset
#
################################################################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

[ $# -ne 0 ] && { gyr-print -e ${0##*/} "Syntax error"; exit 1; }

if [ -f ~/.yaql.pid ]; then
    zenity  --question --title "Alert"  --text "Reset xterm-dropdown?"
    if [ $? -eq 0 ]; then
        kill $(cat ~/.yaql.pid) && rm -rf ~/.yaql.pid && xterm -e ${GYR_PATH}/scripts/gyr-screen XTERMDROPDOWN
    fi
fi
