#!/usr/bin/env bash
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gustavoyr+scripts AT gmail DOT com>
# File:  gyr-switch-window
# Update: 20110428 10:53:20
# (C) Copyright 2011 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Graphical switch window.
# Usage: gyr-switch-window [window_name]
#
################################################################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

[ $# -gt 1 ] && { gyr-print -e ${0##*/} "Syntax error!"; exit 1; }

[ $# -eq 1 ] && WIN=$1 || WIN=$(zenity --entry --title="wido" --text="Switch to window?")

wmctrl -a ${WIN}
if [ $? -eq 1 ]; then
    wmctrl -x -a ${WIN}
fi
