#!/usr/bin/env sh
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gyr AT protonmail DOT ch>
# File:  gyr-pip-update-all
# Update: 20161209
# (C) Copyright 2016 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: 
# Usage: 
#
################################################################################

# Always exit on errors
set -e
# Undefined variables, we don't like you
#set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

pip install --user --upgrade pip
pip freeze --local --user | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install --user --upgrade
