#!/usr/bin/env bash
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gustavoyr+scripts AT gmail DOT com>
# File:  gyr-gnome-reset
# Update: 20111002
# (C) Copyright 2011 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Reset gnome configuration
# Usage: gyr-gnome-reset
#
################################################################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

[ $# -ne 0 ] && { gyr-print -e ${0##*/} "Syntax error"; exit 1; }

read -p "Reset gnome configuration? [y/N] "
if [[ "${REPLY}" =~ [Yy] ]]; then
    TEMP_DIR=$(mktemp -d)
    echo "Moving all your gnome config directories to ${TEMP_DIR} (temporary directory)"
    mv ~/.gnome ~/.gnome2 ~/.gconf ~/.gconfd ~/.metacity ${TEMP_DIR}
    ls -la ${TEMP_DIR}
fi
