#!/usr/bin/env bash
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gyr AT protonmail DOT ch>
# File:  gyr-ip-get
# Update: 20120119
# (C) Copyright 2012 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Display IP (inet) of the given interface
# Usage: gyr-ip-get <network_interface>
#
################################################################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

[ $# -ne 1 ] && { gyr-print -e ${0##*/} "Syntax error"; exit 1; }

if ip address show dev $1 > /dev/null 2>&1; then
    ip address show dev $1 | sed -n -e 's/ *inet \+\(.*\)\/.*$/\1/p'
fi
