#!/usr/bin/env bash

echo -e "\e[32m"
while $t; do
    for i in `seq 1 30`; do
        r="$[($RANDOM % 2)]"
        h="$[($RANDOM % 4)]"
        if [ $h -eq 1 ]; then
            v="\e[1m $r"
        else
            v="\e[2m $r"
        fi;
        v2="$v2 $v"
    done;
    echo -e $v2
    v2=""
done
