#!/usr/bin/env bash
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gyr AT protonmail DOT ch>
# File:  gyr-redshift
# Update: 20110627
# (C) Copyright 2011 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Wrapper for redshift
# Usage: gyr-redshift
#
################################################################################

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

#pkill ^redshift ||:
#redshift -l -22.50:-47.00 -t 6500:5500 -m vidmode &

# based on my-redshift from joey hess 
if ! pidof redshift; then
    exec redshift -l 23:-47 -r -t 5800:3000 -g 0.9 &
else
    killall redshift ||:
fi
