#!/bin/bash
##################################
#
# Author: Gustavo Yokoyama Ribeiro
# File:   gyr-grep
# Update: 20100815 14:29:17
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Recursive grep.
# Usage: gyr-grep [-grep_options] <string_pattern> [file_pattern]
#
##################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

PARAM="-sI --color"

if [[ $# -ge 2 && "$1" =~ -.* ]]; then
    PARAM="${PARAM} $1"
    shift 1
fi

case $# in
    1)
        STR_PATTERN=$1
        FILE_PATTERN="*"
        ;;
    2)
        STR_PATTERN=$1
        FILE_PATTERN=$2
        ;;
    *)
        gyr-print -e ${0##*/}
        exit 1
        ;;
esac

if [[ -n "${STR_PATTERN}" ]]; then
    find . -type f -iname "${FILE_PATTERN}" -not -name "*\'*" -print0 | xargs -0r grep ${PARAM} ${STR_PATTERN} 2> /dev/null
fi
