#!/usr/bin/env bash
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gustavoyr+vim AT gmail DOT com>
# File:  gyr-shutdown
# Update: 20141103
# (C) Copyright 2014 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Hibernate wrapper.
# Usage: gyr-shutdown
#
################################################################################

[ $# -eq 1 -a "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

# hibernate system
read -p "Shutdown? [y/N] "
if [[ "${REPLY}" =~ [Yy] ]]; then
    gyr-print -i "Finishing schroot..."
    schroot --end-session --chroot gyr-schroot-session --force
    gyr-print -i "Starting shutdown..."
    sudo systemctl poweroff
    #sudo systemctl hatl
fi
