#!/usr/bin/env bash
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gustavoyr+scripts AT gmail DOT com>
# File:  gyr-launcher
# Update: 20110818
# (C) Copyright 2011 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: run command in background with nohup
# Usage: gyr-launcher <command>
#
################################################################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

[ $# -eq 0 ] && { gyr-print -e ${0##*/} "Syntax error"; exit 1; }

LOG_DIR="${HOME}/.launcher.d"
[ ! -d ${LOG_DIR} ] && mkdir -p ${LOG_DIR}
logfilename="${LOG_DIR}/${1##*/}_$(date +%Y%m%d_%H%M%S)"
echo "== LAUNCH $@ ==" > ${logfilename}_stdout.log
echo "== LAUNCH $@ ==" > ${logfilename}_stderr.log
nohup "$@" >>${logfilename}_stdout.log 2>>${logfilename}_stderr.log &
