#!/bin/bash
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gustavoyr+scripts AT gmail DOT com>
# File:  gyr-encrypt
# Update: 20100815 14:28:51
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Encrypt file.
# Usage: gyr-encrypt <unencrypted_input_file>
#
################################################################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

[ $# -ne 1 ] && { gyr-print -e ${0##*/}; exit 0; }
[ ! -f $1 ] && { gyr-print -e ${0##*/} "$1 is not a file."; exit 1; }

#openssl des3 -salt -in $1 -out $1.des3
openssl aes-256-cbc -a -salt -in $1 -out $1.enc

# or
#gpg -c $1
