#!/usr/bin/env bash
###############################################################
#
# Author: Gustavo Yokoyama Ribeiro <gustavoyr+scripts AT gmail DOT com>
# File:   gyr-diff-3
# Update: 20100815 14:13:26
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: directory diff
# Usage: gyr-diff-3 <dir_name_1> <dir_name_2>
#
###############################################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

[ $# -ne 2 ] && { gyr-print -e ${0##*/}; exit 1; }
[ ! -d $1 -o ! -d $2 ] && { gyr-print -e ${0##*/} "Invalid directory"; exit 1; }

diff -rq $1 $2 #| awk '/differ/ {print "echo "$2" "$4}'
