#!/usr/bin/env bash
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gustavoyr+scripts AT gmail DOT com>
# File: gyr-time-measure
# Update: 20110222 16:57:51
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Return the second spend by a command to execute
# Usage: gyr-time-measure [-t] <program>
#   -t: format output to HH:MM:SS
#
################################################################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

while getopts ':t' OPT_NAME 2> /dev/null; do
    case ${OPT_NAME} in
        't')
            FORMAT=1
        ;;
        '?')
            gyr-print -e  "Invalid option: -${OPTARG}."
            exit 1
        ;;
        ':')
            gyr-print -e  "Required argument not found for option -${OPTARG}."
            exit 1
        ;;
        *)
            gyr-print -e  "Unknown error while processing options."
            exit 1
        ;;
    esac
done
(( OPTIND > 1 )) && shift $(( OPTIND - 1 ))

[ $# -eq 0 ] && { gyr-print -e ${0##*/}; exit 1; }

START_TIME=$(date +%s)
$@
END_TIME=$(date +%s)
RESULT_TIME=$(( END_TIME - START_TIME ))
if [[ ${FORMAT} -eq 1 ]]; then
    FORMAT_RESULT_TIME=$((10800 + RESULT_TIME))
    RESULT_TIME=$(date -d @${FORMAT_RESULT_TIME} +%H:%M:%S)
fi
echo ${RESULT_TIME}
