#!/usr/bin/env bash
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gyr AT protonmail DOT ch>
# File:  gyr-transparent-unset
# Update: 20111208
# (C) Copyright 2011 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Set window transparence
# Usage: gyr-transparent-unset [${WINDOWID}]
#
################################################################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

case $# in
    0)
        WINID=${WINDOWID}
        ;;
    1)
        WINID=$1
        ;;
    *)
        { gyr-print -e ${0##*/} "Syntax error!"; exit 1; }
        ;;
esac

( ps nc -C xcompmgr &>/dev/null ) || xcompmgr &
#transset-df -i ${WINID} 1
xprop -frame -f _NET_WM_WINDOW_OPACITY 32c -remove _NET_WM_WINDOW_OPACITY -id ${WINDOWID}
