#!/bin/bash
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gustavoyr+scripts AT gmail DOT com>
# File:  gyr-cmus
# Update: 20101123 14:51:43
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: cmus wrapper
# Usage: gyr-cmus
#
################################################################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

[ $# -ne 0 ] && { gyr-print -e ${0##*/}; exit 1; }

DIR_NAME='/work/gyr/.confm'

if ! mount | cut -d ' ' -f1 | grep ${DIR_NAME} >/dev/null 2>&1; then
    sudo mount -t ecryptfs ${DIR_NAME} ${DIR_NAME} -o key=passphrase,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_passthrough=n,ecryptfs_enable_filename_crypto=yes
fi

if mount | cut -d ' ' -f1 | grep /work/gyr/.confm >/dev/null 2>&1; then
    cmus
fi
