#!/bin/sh

tmpfile=$(mktemp) && echo -e 'startup_message off\nscreen -t messages bash -c "sudo tail -f /var/log/messages"\nsplit\nfocus\nscreen -t syslog bash -c "sudo tail -f /var/log/syslog"\nsplit\nfocus\nscreen -t dmesg bash -c "sudo cat /proc/kmsg"\nfocus' > $tmpfile && sudo screen -c $tmpfile
