#!/usr/bin/env bash
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gyr AT protonmail DOT ch>
# File:  gyr-decrypt
# Update: 20100815 14:28:05
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: decrypt file
# Usage: gyr-decrypt <encrypted_input_file>
#
################################################################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

[ $# -ne 1 ] && { gyr-print -e ${0##*/}; exit 0; }
[ ! -f $1 ] && { gyr-print -e ${0##*/} "$1 is not a file."; exit 1; }

if [ "$1" == "${1%%.enc}" ]; then
    OUTFILE="${1}.dec"
else
    OUTFILE="${1%%.enc}"
fi
#openssl des3 -d -salt -in $1 -out ${1%%.des3}
openssl aes-256-cbc -d -a -salt -in $1 -out ${OUTFILE}

# or
#gpg $1
