#!/usr/bin/env bash
########################################################
#
# Author: Gustavo Yokoyama Ribeiro <gyr AT protonmail DOT ch>
# File:   gyr-rpm-unpack
# Update: 20100815 14:23:59
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: unpack rpm files.
# Usage: gyr-rpm-unpack <full_path_rpm_file_name> <dest_dir>
#
########################################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

[ $# -ne 2 ] && { gyr-print -e ${0##*/}; exit 1; }

RPM_FILE=$1
DEST_DIR=$2
[ ! -d ${DEST_DIR} ] && mkdir ${DEST_DIR}

cd ${DEST_DIR}
rpm2cpio ${RPM_FILE} | cpio -ivmud
cd -
