#!/bin/bash
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gustavoyr+scripts AT gmail DOT com>
# File:  gyr-afuse
# Update: 20120213
# (C) Copyright 2012 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: 
# Usage: 
#
################################################################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

fusermount -u -z /home/work/remote/

afuse -o mount_template="sshfs -o reconnect %r: %m" -o unmount_template="fusermount -u -z %m" -o timeout=60 /home/work/remote/
