#!/usr/bin/env bash

echo hello

# Parse command line options.
# Execute the following if --log is seen.
if test -t 1; then
    # Stdout is a terminal.
    exec >log
    #exec >log 2>&1
else
    # Stdout is not a terminal, no logging.
    false
    #npipe=/tmp/$$.tmp
    #trap "rm -f $npipe" EXIT
    #mknod $npipe p
    #tee <$npipe log &
    #exec 1>&-
    #exec 1>$npipe
fi

echo goodbye
#echo error >&2
