#!/usr/bin/env bash
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gustavoyr+scripts AT gmail DOT com>
# File:  gyr-rsync-auto
# Update: 20110928
# (C) Copyright 2011 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Sync tool for ${HOME} directory
# Usage: gyr-rsync-auto
#
################################################################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

[ $# -ne 0 ] && { gyr-print -e ${0##*/} "Syntax error!"; exit 1; }

echo "WARNING: Remote host MUST have a /work/gyr directory!!!"
read -p "Enter remote host (empty exits): "
[ -z ${REPLY} ] && exit 0 || REMOTE_HOST=${REPLY}
if ! ping -c 2 ${REMOTE_HOST} > /dev/null 2>&1; then
    { gyr-print -e ${0##*/} "Invalid host ${REMOTE_HOST}"; exit 1; }
fi

REMOTE_DIR='/work'
LOCAL_DIR="$HOME/work/annex"
gyr-print -i "Sync'ing ${LOCAL_DIR} -> ${REMOTE_HOST}:${REMOTE_DIR}"
rsync -Cavz --update --delete ${LOCAL_DIR} ${REMOTE_HOST}:${REMOTE_DIR}
#LIST_DIR=".gnupg .gyr.d .ibm.d .purple .xchat2"
#
#for i in ${LIST_DIR}; do
#    gyr-print -i "Sync'ing ${LOCAL_DIR}/$i -> ${REMOTE_HOST}:${REMOTE_DIR}/"
#    rsync -Cavz --update --delete ${LOCAL_DIR}/${i} ${REMOTE_HOST}:${REMOTE_DIR}/
#    # -C, --cvs-exclude
#    # -a, --archive (is equivalent to -rlptgoD)
#    # -v, --verbose
#    # -z, --compress
#done

#LIST_DIR="lotus Documents SametimeMeetings SametimeRooms"
#LOCAL_DIR=$HOME
#for i in ${LIST_DIR}; do
#    gyr-print -i "Sync'ing ${LOCAL_DIR}/$i -> ${REMOTE_HOST}:${REMOTE_DIR}/"
#    rsync -Cavz --update --delete ${LOCAL_DIR}/${i} ${REMOTE_HOST}:${REMOTE_DIR}/
#    # -C, --cvs-exclude
#    # -a, --archive (is equivalent to -rlptgoD)
#    # -v, --verbose
#    # -z, --compress
#done
