#!/usr/bin/env bash
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gyr AT protonmail DOT ch>
# File:  gyr-base-conversor
# Update: 20130321
# (C) Copyright 2013 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Convert a decimal number to hexa, octal and binary
# Usage: gyr-base-conversor <decimal_number>
#
################################################################################

[ $# -eq 1 -a "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

[ $# -ne 1 ] && { gyr-print -e ${0##*/} "Syntax error."; exit 1; }

echo "Decimal: $1"

printf 'Hexadecimal: %x\n' $1 # para hexadecimal
#printf '%X\n' $1

printf 'Octal: %o\n' $1 # para octal

bc <<< "obase=2;$1" # para binario

#bc <<< "obase=21;$1" # para base 21 -> QUALQUER BASE!

#echo $((844)) # decimal
#echo $((0x34c)) # hexadecimal
#echo $((01514)) # octal
#echo $((2#1101001100)) # binario
#echo $((21#1j4)) # base 21 -> QUALQUER BASE!
