#!/usr/bin/env bash
##################################
#
# Author: Gustavo Yokoyama Ribeiro
# File:   gyr-print-helper
# Update: 20100815 14:31:22
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Print help information for a command.
# Usage: gyr-print-helper <full_path_command>
#
##################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

# Always exit on errors
set -e
# Undefined variables, we don't like you
set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

[ $# -ne 1 ] && { gyr-print -e "${0##*/}"; exit 1; }
[ -f $1 ] || { gyr-print -e ${0##*/} "Can not read $1. No such file."; exit 1; }

#tput setaf 7
sed -n '
s/#\( \|\)//
/^Description: /p
/^Usage: /,/^$/p
' $1
#sed -n\
#    -e 's/#\( \|\)//'\
#    -e '/^Description: /p'\
#    -e '/^Usage: /,/^$/p'\
#    $1
#tput sgr0
