#!/bin/zsh
##################################
#
# Author: Gustavo Yokoyama Ribeiro
# File:   createCtags
# Update: 20080414 11:52:44
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Generate ctag file.
# Usage: createCtags <-iwgdlua>
#   -i: ctag for IMPS.
#   -w: ctag for WVIM.
#   -g: ctag for GHDR.
#   -d: ctag for DL.
#   -l: ctag for LJ.
#   -u: ctag for UTIL.
#   -a: ctag for all IMPS
#
###################################

[[ -z ${CLEARCASE_ROOT} ]] && { gyr-print -e "$0:t" "view not set."; exit 1; }

[[ $# -eq 1 && $1 == "--help" ]] && { gyr-print-helper $0; exit 0; }

trap "/bin/rm -vf /vobs/core_imps/code/im/*_tags" 1 2 3 15

BASE_DIR='/vobs/core_imps/code/im'

targets=(
${BASE_DIR}/imps_tags
${BASE_DIR}/wvim_tags
${BASE_DIR}/ghdr_tags
${BASE_DIR}/dl_tags
${BASE_DIR}/lj_tags
${BASE_DIR}/util_tags)

code_dirs=(
/vobs/core_imps/code/im/imps
/vobs/core_imps/code/im/wvim/hdr
/vobs/core_imps/code/im/ghdr
'/vobs/core_imps/code/im/dl_hdr/src /vobs/core_imps/code/im/dl_util/src /vobs/core_imps/code/im/dl_wvim/src'
/vobs/core_imps/code/im/lj
/vobs/core_imps/code/im/util/hdr /vobs/core_imps/code/im/public)

while getopts ':iwgdlua' OPT_NAME 2> /dev/null; do
    case ${OPT_NAME} in
    'i')
        START_DIR=1
        END_DIR=${START_DIR}
        ;;
    'w')
        START_DIR=2
        END_DIR=${START_DIR}
        ;;
    'g')
        START_DIR=3
        END_DIR=${START_DIR}
        ;;
    'd')
        START_DIR=4
        END_DIR=${START_DIR}
        ;;
    'l')
        START_DIR=5
        END_DIR=${START_DIR}
        ;;
    'u')
        START_DIR=6
        END_DIR=${START_DIR}
        ;;
    'a')
        START_DIR=1
        END_DIR=${#targets}
        ;;
    '?')
        gyr-print -e ${0##*/} "Invalid option: -${OPTARG}."
        exit 1
        ;;
    ':')
        gyr-print -e ${0##*/} "Required argument not found for option -${OPTARG}."
        exit 1
        ;;
    *)
        gyr-print -e ${0##*/} "Unknown error while processing options."
        exit 1
        ;;
    esac
done

[[ ${OPTIND} -eq 1 || $# -gt 1 ]] && { gyr-print -e "$0:t"; exit 1; }

ctags_options=(-R --c++-kinds=+p --fields=+iaS --extra=+q -h \".h\",\".hh\" -f)
CTAGS_BIN="/work/wgr014/ctags/bin/ctags"

# Multiple files
COUNT_DIR=${START_DIR}
#while [[ ${COUNT_DIR} -le ${END_DIR} ]]
while (( ${COUNT_DIR} <= ${END_DIR} ))
do
    gyr-echo "Generating ${targets[${COUNT_DIR}]} ctag file..."
    rm -vf ${targets[${COUNT_DIR}]}
    ${CTAGS_BIN} ${ctags_options} ${targets[${COUNT_DIR}]} ${(z)code_dirs[${COUNT_DIR}]} && gyr-echo "Generating ${targets[${COUNT_DIR}]} ctag file... done" || gyr-echo "Generating ${targets[${COUNT_DIR}]} ctag file... failed"
#    COUNT_DIR=$((${COUNT_DIR}+1))
    (( COUNT_DIR++ ))
done

# Single file
#gyr-echo "Generating ${targets[1]} ctag file..."
#rm -vf ${targets[1]}
#${CTAGS_BIN} ${ctags_options} ${targets[${START_DIR},${END_DIR}]} ${code_dirs[${START_DIR},${END_DIR}]}
#gyr-echo "Generating ${targets[1]} ctag file...done"
