#!/bin/zsh
##################################
#
# Author: Gustavo Yokoyama Ribeiro
# File:   createList
# Update: 20080318 16:54:45
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Create list of all files.
# Usage: createList
#
##################################

[[ -z ${CLEARCASE_ROOT} ]] && { gyr-print -e "$0:t" "view not set."; exit 1; }

[[ $# -eq 1 && $1 == "--help" ]] && { gyr-print-helper $0; exit 0; }
[[ $# -ne 0 ]] && { gyr-print -e "$0:t"; exit 1; }

BASE_PATH='/vobs/core_imps/code/im/'
FILE_REGEXP='.*\.\(pro\|[hH]\|c\|cc\|cpp\)'
FILE_LIST="${BASE_PATH}/fileList"

rm -vf ${FILE_LIST}
find ${BASE_PATH} -type f -regex "${FILE_REGEXP}" -print > ${FILE_LIST}
