#!/bin/zsh
##################################
#
# Author: Gustavo Yokoyama Ribeiro
# File:   glog
# Update: 20080327 13:03:04
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Show the latest build log.
# Usage: glog
#
###################################

[[ $# -eq 1 && $1 == "--help" ]] && { gyr-print-helper $0; exit 0; }
[[ $# -ne 0 ]] && { gyr-print -e "$0:t"; exit 1; }

DIR_LOG="${HOME}/bldlogs"
#/bin/ls -tr ~/bldlogs | tail -n 1 | xargs -i less ~/bldlogs/{}
#tail -n 1 <(ls -tr ${DIR_LOG}) | xargs -ri less ${DIR_LOG}/{}
less ${*:-${DIR_LOG}/*(om[1])}
