#!/bin/zsh
##################################
#
# Author: Gustavo Yokoyama Ribeiro
# File:   livre
# Update: 20071008 10:04:28
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
#
##################################

ls -l /usr/local_linux/ec/idler_sshlx.txt | awk '{print $9" "$8" "$6" "$7}'
sed 's/rdlinux51/rdlinux51 <<<<</' <<< `cat -n /usr/local_linux/ec/idler_sshlx.txt`
#awk '{if ($2~/rdlinux51/) {print $0"<<<<"} else {print $0}}' <<< `cat -n /usr/local_linux/ec/idler_sshlx.txt`
