#!/bin/bash
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gyr AT protonmail DOT ch>
# File:  gyr-sync-dropbox
# Update: 20110406 15:04:00
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Sync ~/.gyr.d with dropbox dir, excluding .hg dir
# Usage: gyr-sync-dropbox
#
################################################################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

[ $# -ne 0 ] && { gyr-print -e ${0##*/}; exit 1; }

if [ -d ~/Dropbox ]; then
    rsync -avz --delete --exclude '~/.gyr.d/.hg/*' ~--exclude '~/.gyr.d/.git/*' /.gyr.d ~/Dropbox
fi
