#!/bin/bash
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gustavoyr+scripts AT gmail DOT com>
# File:  gyr-dropbox-recover
# Update: 20120127
# (C) Copyright 2012 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Restore dropbox files
# Usage: gyr-dropbox-recover
#
################################################################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

GYR_DOT_DIR=${HOME}/.gyr.d
if [ -L "${GYR_DOT_DIR}" -o ! -d "${GYR_DOT_DIR}" ]; then
    if [ -d /work/gyr/.gyr.d -a ! -L /work/gyr/.gyr.d ]; then
        GYR_DOT_DIR=/work/gyr/.gyr.d
    else
        gyr-print -e ${0##*/} "Invalid recovery dir (.gyr.d)"
        exit 1
    fi
fi

DIR_DROPBOX=${HOME}/Dropbox
if [ ! -d "${DIR_DROPBOX}" ]; then
    DIR_DROPBOX=/work/gyr/Dropbox
    if [ ! -d "${DIR_DROPBOX}" ]; then
        gyr-print -e ${0##*/} "Invalid Dropbox dir (${DIR_DROPBOX})"
        exit 1
    fi
fi

DIR_DEC_BKP=${DIR_DROPBOX}/bkp/bkpc
if [ ! -d "${DIR_DEC_BKP}" ]; then
    gyr-print -e ${0##*/} "Invalid Dropbox dir (${DIR_DEC_BKP})"
    exit 1
fi

DIR_ENC_BKP=${DIR_DROPBOX}/.bbb
if [ -d "${DIR_ENC_BKP}" ]; then
    if ! mount | cut -d ' ' -f1 | grep ${DIR_ENC_BKP} >/dev/null 2>&1; then
        sudo mount -t ecryptfs ${DIR_ENC_BKP} ${DIR_DEC_BKP} -o key=passphrase,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_passthrough=n,ecryptfs_enable_filename_crypto=y
    fi
else
    gyr-print -e ${0##*/} "Invalid Dropbox dir (${DIR_ENC_BKP})"
    exit 1
fi

ls -la ${DIR_DEC_BKP}/.gyr.d/ || { gyr-print -e ${0##*/} "Failed to mount ${DIR_DEC_BKP}"; exit 1; }
echo "Dropbox dir: ${DIR_DEC_BKP}/.gyr.d/"
echo "Recovery dir: ${GYR_DOT_DIR}/"
read -p "Proceed recovery? [y/N] "
if [[ "${REPLY}" =~ [Yy] ]]; then
    rsync -Cravzpt --delete ${DIR_DEC_BKP}/.gyr.d/ ${GYR_DOT_DIR}/
fi
