#!/bin/bash
################################################################################
#
# Author: Gustavo Yokoyama Ribeiro <gyr AT protonmail DOT ch>
# File:  gyr-dropbox-start
# Update: 20110707
# (C) Copyright 2011 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: dropbox wrapper
# Usage: gyr-dropbox-start
#
################################################################################

[ "$1" = '--help' ] && { gyr-print-helper $0; exit 0; }

[ $# -ne 0 ] && { gyr-print -e ${0##*/}; exit 1; }

DIR_MOUNTED='/work/gyr/Dropbox/.bbb'

if [ -d "${DIR_MOUNTED}" ]; then
    if mount | cut -d ' ' -f1 | grep ${DIR_MOUNTED} >/dev/null 2>&1; then
        sudo umount ${DIR_MOUNTED} || { gyr-print -e ${0##*/} "Failed to umount ${DIR_MOUNTED}"; exit 1; }
    fi
else
    gyr-print -e ${0##*/} "Source dir ${DIR_MOUNTED} does not exist."
    exit 1
fi

#dropbox start -i
~/.dropbox-dist/dropboxd &
