#!/bin/zsh
##################################
#
# Author: Gustavo Yokoyama Ribeiro
# File:   clearView
# Update: 20080424 16:01:39
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Delete and create a new view with the same cs.
# Usage: clearView [view_pattern|view_name]
#
##################################

[[ $# -gt 1 ]] && { gyr-print -e "$0:t"; exit 1; }
[[ $1 == "--help" ]] && { gyr-print-helper $0; exit 0; }

if [[ ${HOST} == rdux0* ]]; then
    UNIX_HOST=${HOST}
else
    UNIX_HOST=rdbdsr01
    echo -n "Unix host: "
    gyr-echo ${UNIX_HOST}
    read -q "?Edit unix host? [ny] " && vared UNIX_HOST
fi

TMP_CS_FILE="/tmp/gyr_tmp_clearView$$.cs"

SELECTED_VIEW=$(getView $1) || { gyr-print -e "$0:t" "${SELECTED_VIEW}"; exit 1; }

[[ -n ${CLEARCASE_ROOT} ]] && [[ ${CLEARCASE_ROOT:t} == ${SELECTED_VIEW} ]] && { gyr-print -e "$0:t" "selected view to delete is the current view."; exit 1; }

if [[ -n ${SELECTED_VIEW} ]]; then
    echo -n "Selected view: "
    gyr-echo ${SELECTED_VIEW}
    if read -q "?Clear view ${SELECTED_VIEW}? [ny] "; then
        gyr-echo "Cleanning view ${SELECTED_VIEW}..."
        PRE_CMD="cleartool catcs -tag ${SELECTED_VIEW} > ${TMP_CS_FILE} && cleartool rmview -tag ${SELECTED_VIEW}"
        MAIN_CMD="[[ -f ${TMP_CS_FILE} ]] && mkviewlj ${SELECTED_VIEW} && cleartool setcs -tag ${SELECTED_VIEW} ${TMP_CS_FILE} && rm -f ${TMP_CS_FILE}"
        remoteCmd ${UNIX_HOST} "${PRE_CMD}" "${MAIN_CMD}" && gyr-echo "Cleanning view ${SELECTED_VIEW}... done" || gyr-echo "Cleanning view ${SELECTED_VIEW}... failed"
    fi
fi
