#!/bin/zsh
##################################
#
# Author: Gustavo Yokoyama Ribeiro
# File:   clearPriv
# Update: 20080319 11:35:40
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Delete all private objects from a view.
# Usage: clearPriv [view_pattern|view_name]
#
##################################

[[ $# -gt 1 ]] && { gyr-print -e "$0:t"; exit 1; }
[[ $1 == "--help" ]] && { gyr-print-helper $0; exit 0; }

if [[ $# -eq 0 && -n ${CLEARCASE_ROOT} ]]; then
    SELECTED_VIEW=${CLEARCASE_ROOT:t}
else
    SELECTED_VIEW=$(getView $1) || { gyr-print -e "$0:t" " ${SELECTED_VIEW}"; exit 1; }
fi

if [[ -n ${SELECTED_VIEW} ]]; then
    echo -n "Selected view: "
    gyr-echo ${SELECTED_VIEW}
    if read -q "?Delete all private elements from ${SELECTED_VIEW}? [ny] "; then
        cleartool setview ${SELECTED_VIEW} << CLR_PRV
for i in $(cleartool lsprivate); { rm -vfr $i; }
CLR_PRV
#PRIV_ELEM=$(cleartool lsprivate)
#for i in ${PRIV_ELEM}; { rm -vfr $i; }
    fi
fi
