#!/bin/zsh
##################################
#
# Author: Gustavo Yokoyama Ribeiro
# File:   cpcs
# Update: 20080414 11:49:08
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Copy config-spec from view source to view target.
# Usage: setcs [source_view_pattern|source_view_name] [target_view_pattern|target_view_name]
#
##################################

#trap "rm -vf /tmp/gyr_source_view_cs$$.cs; exit 1" 1 2 3 15

[[ $# -eq 1 && $1 == "--help" ]] && { gyr-print-helper $0; exit 0; }
[[ $# -ne 2 ]] && { gyr-print -e "$0:t"; exit 1; }

SOURCE_VIEW=$(getView $1) || { gyr-print -e "$0:t" "${SELECTED_VIEW}"; exit 1; }
echo -n "Source view: "
gyr-echo ${SOURCE_VIEW}
TARGET_VIEW=$(getView $2) || { gyr-print -e "$0:t" " ${SELECTED_VIEW}"; exit 1; }
echo -n "Target view: "
gyr-echo ${TARGET_VIEW}

if [[ -n ${SOURCE_VIEW} && -n ${TARGET_VIEW} ]]; then
    if read -q "?Copy config-spec from ${SOURCE_VIEW} to ${TARGET_VIEW}? [ny] ";then
        gyr-echo "Copying config-spec from ${SOURCE_VIEW} to ${TARGET_VIEW}..."
#        cleartool catcs -tag ${SOURCE_VIEW} > /tmp/gyr_source_view_cs$$.cs
#        cleartool setcs -tag ${TARGET_VIEW} /tmp/gyr_source_view_cs$$.cs
        cleartool setcs -tag ${TARGET_VIEW} =(cleartool catcs -tag ${SOURCE_VIEW}) && gyr-echo "Copying config-spec from ${SOURCE_VIEW} to ${TARGET_VIEW}... done" || gyr-echo "Copying config-spec from ${SOURCE_VIEW} to ${TARGET_VIEW}... failed"
#        rm -f /tmp/gyr_source_view_cs$$.cs
    fi
fi
