#!/bin/zsh
##################################
#
# Author: Gustavo Yokoyama Ribeiro
# File:   findMerge
# Update: 20080318 16:51:57
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Clearcase findmerge wrapper.
# Usage: findMerge <vob_pathname> <label|branch> <-a|-m|-p>
#   -a: automatic merge.
#   -m: manual merge.
#   -p: print.
#
##################################

[[ -z ${CLEARCASE_ROOT} ]] && { gyr-print -e "$0:t" "view not set."; exit 1; }

[[ $# -eq 1 && $1 == "--help" ]] && { gyr-print-helper $0; exit 0; }
[[ $# -ne 3 ]] && { gyr-print -e "$0:t"; exit 1; }

case $3 in
    '-a') cleartool findmerge $1 -fversion $2 -merge -gmerge;;
    '-m') cleartool findmerge $1 -fversion $2 -okgm -qall;;
    '-p') cleartool findmerge $1 -fversion $2 -print;;
esac
