#!/bin/zsh
##################################
#
# Author: Gustavo Yokoyama Ribeiro
# File:   getView
# Update: 20080319 11:34:08
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Return a view.
# Usage: getView [view_pattern]
#
##################################

[[ $# -gt 1 ]] && { gyr-print -e "$0:t"; exit 1; }
[[ $1 == "--help" ]] && { gyr-print-helper $0; exit 0; }

[[ $# -eq 0 ]] && VIEW=${USER} || VIEW=$1

cleartool lsview -s ${VIEW} 2> /dev/null && exit 0

PS3="Select a view: "
select SELECTED_VIEW in $(cleartool lsview -s | grep ${VIEW} 2> /dev/null); { break; }

[[ -z ${SELECTED_VIEW} ]] && { echo "View not found."; exit 1; } || echo ${SELECTED_VIEW}
