#!/bin/zsh
##################################
#
# Author: Gustavo Yokoyama Ribeiro
# File:   lsbr
# Update: 20080318 16:49:37
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: List all file under the branch in current vob.
# Usage: lsbr <branch_name>
#
##################################

[[ -z ${CLEARCASE_ROOT} ]] && { gyr-print -e "$0:t" "view not set."; exit 1; }

[[ $# -ne 1 ]] && { gyr-print -e "$0:t"; exit 1; }
[[ $1 == "--help" ]] && { gyr-print-helper $0; exit 0; }

cleartool find -all -branch "brtype($1)" -exec 'cleartool desc -s $CLEARCASE_XPN/LATEST'
