#!/bin/zsh
##################################
#
# Author: Gustavo Yokoyama Ribeiro
# File:   lslball
# Update: 20080318 16:51:03
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: List file under label in avobs vob.
# Usage: lslball <label_name>
#
##################################

[[ -z ${CLEARCASE_ROOT} ]] && { gyr-print -e "$0:t" "view not set."; exit 1; }

[[ $# -ne 1 ]] && || { gyr-print -e "$0:t"; exit 1; }
[[ $1 == "--help" ]] && || { gyr-print-helper $0; exit 0; }

cleartool find -avobs -ver "lbtype($1)" -print
