#!/bin/zsh
##################################
#
# Author: Gustavo Yokoyama Ribeiro
# File:   makeView
# Update: 20080424 16:01:30
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Create new view.
# Usage: makeView <view_name>
#
###################################

[[ $# -ne 1 ]] && { gyr-print -e "$0:t"; exit 1; }
[[ $1 == "--help" ]] && { gyr-print-helper $0; exit 0; }

if [[ ${HOST} == rdux0* ]]; then
    UNIX_HOST=${HOST}
else
    UNIX_HOST=rdbdsr01
fi
echo -n "Unix host: "
gyr-echo ${UNIX_HOST}
read -q "?Edit unix host? [ny] " && vared UNIX_HOST

gyr-echo "Creating view $1..."
MAKE_CMD="mkviewlj $1"
remoteCmd ${UNIX_HOST} "${MAKE_CMD}" && gyr-echo "Creating view $1... done" || gyr-echo "Creating view $1...failed"
