#!/bin/zsh
##################################
#
# Author: Gustavo Yokoyama Ribeiro
# File:   mergeInsert
# Update: 20080319 11:36:15
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Insert diff between 2 file versions in the current file.
# Usage: mergeInsert <file_name> <initial_version> <final_version>
#
##################################

[[ -z ${CLEARCASE_ROOT} ]] && { gyr-print -e "$0:t" "view not set."; exit 1; }

[[ $# -eq 1 && $1 == "--help" ]] && { gyr-print-helper $0; exit 0; }
[[ $# -ne 3 ]] && { gyr-print -e "$0:t"; exit 1; }

FILE_CHECKEDOUT=$(cleartool lsco -me $1)

[[ -z ${FILE_CHECKEDOUT} ]] &&  { gyr-print -e "$0:t" "file not CHECKEDOUT."; exit 1; }

cleartool merge -to $1 -g -insert -version $2 $3
