#!/bin/zsh
##################################
#
# Author: Gustavo Yokoyama Ribeiro
# File:   rmView
# Update: 20080414 11:55:16
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Delete a view.
# Usage: rmView [view_pattern|view_name]
#
##################################

[[ $# -gt 1 ]] && { gyr-print -e "$0:t"; exit 1; }
[[ $1 == "--help" ]] && { gyr-print-helper $0; exit 0; }

SELECTED_VIEW=$(getView $1) || { gyr-echo "$0:t - ${SELECTED_VIEW}"; exit 1; }

[[ -n ${CLEARCASE_ROOT} ]] && [[ ${CLEARCASE_ROOT:t} == ${SELECTED_VIEW} ]] && { gyr-print -e "$0:t" "selected view to delete is the current view."; exit 1; }

if [[ -n ${SELECTED_VIEW} ]]; then
    echo -n "Selected view: "
    gyr-echo ${SELECTED_VIEW}
    read -q "?Delete view ${SELECTED_VIEW}? [ny] " && { gyr-echo "Deleting view ${SELECTED_VIEW}..."; cleartool rmview -tag ${SELECTED_VIEW} && gyr-echo "Deleting view ${SELECTED_VIEW}... done" || gyr-echo "Deleting view ${SELECTED_VIEW}... failed"; }
fi
