#!/bin/zsh
##################################
#
# Author: Gustavo Yokoyama Ribeiro
# File:   scsv
# Update: 20080319 11:35:18
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Set a view in a new screen.
# Usage: scsv [view_pattern|view_name]
#
##################################

[[ $# -gt 1 ]] && { gyr-print -e "$0:t"; exit 1; }
[[ $1 == "--help" ]] && { gyr-print-helper $0; exit 0; }

if [[ $# -eq 0 && -n ${CLEARCASE_ROOT} ]]; then
    SELECTED_VIEW=${CLEARCASE_ROOT:t}
else
    SELECTED_VIEW=$(getView $1) || { gyr-print -e "$0:t" "${SELECTED_VIEW}"; exit 1; }
fi

if [[ -n ${SELECTED_VIEW} ]]; then
    cd
    screen -t "${SELECTED_VIEW} |$(echo ${SELECTED_VIEW}):" cleartool setview ${SELECTED_VIEW}
fi
