#!/bin/zsh
##################################
#
# Author: Gustavo Yokoyama Ribeiro
# File:   xcd0
# Update: 20080319 11:35:49
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Diff current file and bubble zero version file.
# Usage: xcd0 <file_name>
#
##################################

[[ $# -ne 1 ]] && { gyr-print -e "$0:t"; exit 1; }
[[ $1 == "--help" ]] && { gyr-print-helper $0; exit 0; }

ZERO_FILE=$(cleartool ls -short $1)

xcleardiff -b -vst ${ZERO_FILE%/*}/0 $1
