#!/bin/zsh
##################################
#
# Author: Gustavo Yokoyama Ribeiro
# File:   xcdl
# Update: 20080318 16:49:16
# (C) Copyright 2010 Gustavo Yokoyama Ribeiro
# Licensed under CreativeCommons Attribution-ShareAlike 3.0 Unsupported
# http://creativecommons.org/licenses/by-sa/3.0/ for more info.
# Description: Diff current file and the label version file.
# Usage: xcdl <file_name> <label_name>
#
##################################

[[ $# -eq 1 && $1 == "--help" ]] && { gyr-print-helper $0; exit 0; }
[[ $# -ne 2 ]] && { gyr-print -e "$0:t"; exit 1; }

xcleardiff -b -vst "$1@@/$2" $1
